plugins {
    id 'java'
}

group = 'me.sangjun.aegis'
version = '1.0-SNAPSHOT'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation "me.sangjun.aegis:aegis-core:0.0.1-SNAPSHOT"
    implementation "ch.qos.logback:logback-classic:1.5.6"

}

test {
    useJUnitPlatform()
}
