plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'me.sangjun.aegis'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation("org.slf4j:slf4j-api:2.0.12")
    implementation("io.github.classgraph:classgraph:4.8.168")
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
